//modules encapsulated code (only share minimum)

const names = require("./4-names")
const sayHi = require("./5-names")
const data = require("./6-alternative")
console.log(names)
require("./7-mind-grenade")
sayHi("susan")
sayHi(names.john)
sayHi(names.peter)
